[build]
  publish = "."
  functions = "netlify/functions"

[dev]
  port = 8890
  staticServerPort = 3998
  autoLaunch = false

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
